version: '3'
services:
  qgis:
    image: mvilche/qgis-desktop:3-bionic
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD/qgis:/home/qgis
    environment: 
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - USER_ID=1000
    networks:
      - integracion
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"

networks:                            
  integracion:                         
